spring:
  # 환경 변수 설정
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:tcp://${DB_URL}/~/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 개발할 때만 사용
    properties:
      hibernate:
        format_sql:


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace