#on:
#  push:
#    branch:
#      - main
#
#
#jobs:
#  CI-CD-TEST:
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: Set up SSH key
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.SPRING_SERVER_KEY }}" > ~/.ssh/yoo
#          sudo chmod 600 ~/.ssh/yoo
#
#      - name: Add EC2 host to known_hosts
#        run: |
#          ssh-keyscan -H ${{ secrets.SPRING_SERVER_IP }} >> ~/.ssh/known_hosts
#
#      - name: EC2 접속하기
#        run: |
#          ssh -i ~/.ssh/yoo ubuntu@${{ secrets.SPRING_SERVER_IP }} << 'EOF'
#            touch ~/hello.txt  # 파일이 없으면 생성
#            echo "접속 성공: $(date)" >> ~/hello.txt
#          EOF