name: mooboo-backend-spring-server dev env CI-CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: resources 폴더 생성
        run: mkdir -p ./src/main/resources

      - name: application-local.yml 파일 만들기 개발 환경
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: application-local.yml 파일 만들기 개발 환경
        run: echo "${{ secrets.APPLICATION_PROPERTIES_LOCAL }}" > ./src/main/resources/application-local.yml

      - name: application-dev.yml 파일 만들기 개발 환경
        run: echo "${{ secrets.APPLICATION_PROPERTIES_DEV }}" > ./src/main/resources/application-dev.yml

      - name: test/resources 폴더 생성
        run: mkdir -p ./src/test/resources

      - name: application-local.yml 파일 만들기 개발 환경
        run: echo "${{ secrets.APPLICATION_PROPERTIES_TEST }}" > ./src/test/resources/application.yml

      - name: GitAction에 Mysql 설정 빌드하기 위함
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.4'
          mysql database: ${{ secrets.DB_NAME }}
          mysql root password: ${{ secrets.ROOT_PASSWORD }}
          mysql user: ${{ secrets.DB_USER }}
          mysql password: ${{ secrets.DB_PASSWORD }}

      - name: Set Spring Profile
        run: echo "SPRING_PROFILES_ACTIVE=dev" >> $GITHUB_ENV

      - name: Debug Spring Profile
        run: printenv | grep SPRING_PROFILES_ACTIVE

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -Dspring.profiles.active=dev

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./mooboo.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: mooboo.jar
          target: /home/ubuntu/mooboo-spring/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/mooboo-spring/current
            mkdir /home/ubuntu/mooboo-spring/current
            mv /home/ubuntu/mooboo-spring/tobe/mooboo.jar /home/ubuntu/mooboo-spring/current/mooboo.jar
            cd /home/ubuntu/mooboo-spring/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar -Dspring.profiles.active=dev mooboo.jar > ./output.log 2>&1 & 
            rm -rf /home/ubuntu/mooboo-spring/tobe